name: biblioqr_app
description: "Aplicación Flutter para gestión de préstamos de libros."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

  # 🔹 Firebase y Firestore
  firebase_core: ^4.9.0
  cloud_firestore: ^6.4.1
  firebase_auth: ^6.5.1

  # 🔹 Notificaciones locales
  flutter_local_notifications: ^21.0.0

  # 🔹 Íconos de Cupertino
  cupertino_icons: ^1.0.8

  # 🔹 QR y escaneo (AndroidX)
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0

  # 🔹 Manejo de zona horaria para notificaciones
<<<<<<< HEAD
  timezone: ^0.11.0       # ✅ versión compatible con notificaciones
  flutter_application_1: ^0.0.2
=======
  timezone: ^0.11.0
>>>>>>> 4bd816215dc2b514361a5b29cbfde8577ed4828e

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/